  main[m
  task/issue-26/view-all-active-bids[m
  task/issue-50/bidding-mechanism_v1[m
  task/issue-54/create-eventbridge-during-auction-creation[m
* [32mtask/issue-58/event-bridge-for-resource-management[m
  [31mremotes/origin/HEAD[m -> origin/main
  [31mremotes/origin/affan/dashboardUI[m
  [31mremotes/origin/issue/swagger-template[m
  [31mremotes/origin/jugal/rds-migration[m
  [31mremotes/origin/main[m
  [31mremotes/origin/task/issue-23/view-auction-details-frontend-ui[m
  [31mremotes/origin/task/issue-24/view-auction-details-backend[m
  [31mremotes/origin/task/issue-25/auction-time-sync[m
  [31mremotes/origin/task/issue-25/auction-time-sync-using-websockets[m
  [31mremotes/origin/task/issue-26/view-all-active-bids[m
  [31mremotes/origin/task/issue-28/create-auction-frontend-ui[m
  [31mremotes/origin/task/issue-29/create-auction-backend-api[m
  [31mremotes/origin/task/issue-30/scripts-to-create-s3-buckets-for-each-auction[m
  [31mremotes/origin/task/issue-32/view-all-auctions-backend-api[m
  [31mremotes/origin/task/issue-35/set-up-branch-name-check-on-github[m
  [31mremotes/origin/task/issue-37/integrate-aws-rds-with-flask-app[m
  [31mremotes/origin/task/issue-47/view-all-auction-backend-part2[m
  [31mremotes/origin/task/issue-50/bidding-mechanism_v1[m
  [31mremotes/origin/task/issue-53/edit-auction[m
  [31mremotes/origin/task/issue-54/create-eventbridge-during-auction-creation[m
  [31mremotes/origin/task/issue-55/dynamically-show-bid-placement-buttons-when-the-auction-becomes-active-via-websocket[m
  [31mremotes/origin/task/issue-58/event-bridge-for-resource-management[m
  [31mremotes/origin/task/issue-62/avoiding-repeat-bids[m
  [31mremotes/origin/task/issue-65/eventbridge-script-to-start-auction[m
  [31mremotes/origin/task/issue-69/api-fetching-resolved[m
  [31mremotes/origin/task/requirements-update[m
