openapi: 3.0.3
info:
  title: Live Flash Auctioning System API
  description: Live Flash Auctioning System built using AWS Cloud Services as part of the Cloud Computing course at New York University.
  version: 1.0.0
servers:
  - url: https://your-api-gateway-url/v1
    description: AWS API Gateway

paths:
  /add-auction:
    post:
      summary: Create a new auction
      description: >
        This API allows clients to create a new auction by providing all necessary details
        such as the item name, description, start/end times, and additional configuration.
      tags:
        - Auctions
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddAuctionData'
      responses:
        '201':
          description: Auction Created Successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: integer
                    example: 201
                  status_message:
                    type: string
                    example: Auction created successfully.
                  data:
                    type: object
                    properties:
                      auction_id:
                        type: string
                        example: "7c6931df-415c-4cae-8620-0da4b792cb58"
                      message:
                        type: string
                        example: Your auction has been listed successfully.
        '401':
          description: Unauthorized - Invalid or missing token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
        '403':
          description: Forbidden - User does not have permission to access this resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenResponse'
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorResponse'

  /get-auctions:
    get:
      summary: Fetch auctions by mode
      description: >
        Fetch auctions based on the selected mode. The mode parameter can take the following values:
        - `all_auctions`: Fetch all auctions (default).
        - `upcoming_auctions`: Fetch upcoming auctions.
        - `my_auctions`: Fetch auctions created by the current user.
      tags:
        - Auctions
      parameters:
        - name: mode
          in: query
          required: true
          description: The mode for fetching auctions.
          schema:
            type: string
            enum: [all_auctions, upcoming_auctions, my_auctions]
            default: all_auctions
      responses:
        '200':
          description: Auctions fetched successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: integer
                    example: 200
                  status_message:
                    type: string
                    example: Auctions fetched successfully.
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: string
                          example: "7c6931df-415c-4cae-8620-0da4b792cb58"
                        auction_item:
                          type: string
                          example: Antique Fan
                        auction_desc:
                          type: string
                          example: A rare collector's item.
                        product_images:
                          type: array
                          items:
                            type: string
                            example: https://example.com/image1.jpg
                        base_price:
                          type: number
                          example: 250.0
                        start_time:
                          type: string
                          format: date-time
                          example: "2024-11-16T09:00:00Z"
                        end_time:
                          type: string
                          format: date-time
                          example: "2024-11-17T18:00:00Z"
                        default_time_increment:
                          type: integer
                          example: 5
                        default_time_increment_before:
                          type: integer
                          example: 10
                        stop_snipes_after:
                          type: integer
                          example: 10
                        created_by:
                          type: string
                          example: johndoe@example.com
        '401':
          description: Unauthorized - Invalid or missing token.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UnauthorizedResponse'
        '403':
          description: Forbidden - User does not have permission to access this resource.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ForbiddenResponse'
        '404':
          description: No auctions found for the given mode.
          content:
            application/json:
              schema:
                type: object
                properties:
                  status_code:
                    type: integer
                    example: 404
                  status_message:
                    type: string
                    example: No auctions found for the mode 'all_auctions'.
                  error_details:
                    type: object
                    properties:
                      error_code:
                        type: string
                        example: AUCTIONS_NOT_FOUND
                      error_message:
                        type: string
                        example: No auctions found for the mode 'all_auctions'.
        '500':
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InternalServerErrorResponse'

components:
  schemas:
    AddAuctionData:
      type: object
      properties:
        auction_item:
          type: string
          example: Antique Fan
        auction_desc:
          type: string
          example: An antique table fan, in excellent condition, a rare collector's item.
        product_images:
          type: array
          items:
            type: string
            example: "https://example.com/images/antique-fan1.jpg"
        base_price:
          type: number
          example: 250.0
        start_time:
          type: string
          format: date-time
          example: "2024-11-16T09:00:00Z"
        end_time:
          type: string
          format: date-time
          example: "2024-11-17T18:00:00Z"
        default_time_increment:
          type: integer
          example: 5
        default_time_increment_before:
          type: integer
          example: 10
        stop_snipes_after:
          type: integer
          example: 10
        is_active:
          type: boolean
          example: true
        created_by:
          type: string
          example: johndoe@example.com
    UnauthorizedResponse:
      type: object
      properties:
        status_code:
          type: integer
          example: 401
        status_message:
          type: string
          example: Unauthorized
        error_details:
          type: object
          properties:
            error_code:
              type: string
              example: INVALID_TOKEN
            error_message:
              type: string
              example: Access token is invalid or missing.
    ForbiddenResponse:
      type: object
      properties:
        status_code:
          type: integer
          example: 403
        status_message:
          type: string
          example: Forbidden
        error_details:
          type: object
          properties:
            error_code:
              type: string
              example: ACCESS_DENIED
            error_message:
              type: string
              example: You do not have permission to perform this action.
    InternalServerErrorResponse:
      type: object
      properties:
        status_code:
          type: integer
          example: 500
        status_message:
          type: string
          example: Internal Server Error
        error_details:
          type: object
          properties:
            error_code:
              type: string
              example: SERVER_ERROR
            error_message:
              type: string
              example: An unexpected error occurred. Please try again later.