name: Lint and Format Check

# Trigger the workflow on pull requests or manual triggers.
on:
  pull_request:
  push:
    branches:
      - '**'
  workflow_dispatch:  # Allows you to trigger the workflow manually

jobs:
  lint:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu for the workflow

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Python
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'

    # Step 3: Install dependencies (Black and Flake8)
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install black flake8

    # Step 4: Run Black in check mode (does not modify files, only checks for issues)
    - name: Run Black
      run: black --check .

    # Step 5: Run Flake8 to check for linting issues
    - name: Run Flake8
      run: flake8 .
